# -*- coding: utf-8 -*-
"""launch_training_job.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVxnDuZJV5EozMpvoCukIQ0kT5Kwxdok
"""

!mkdir -p monai-3d-job

!cp brats_segmentation_3d.ipynb monai-3d-job/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile monai-3d-job/requirements.txt
# monai==1.3.0
# nibabel
# einops
# papermill
# jupyter
# matplotlib
# scikit-image
# tensorboard
# torch==2.1.0

# Commented out IPython magic to ensure Python compatibility.
# %%writefile monai-3d-job/run_notebook.py
# import os
# import papermill as pm
# 
# input_nb = "/opt/ml/code/brats_segmentation_3d.ipynb"
# output_nb = "/opt/ml/model/brats_segmentation_3d_executed.ipynb"
# 
# os.makedirs("/opt/ml/model", exist_ok=True)
# 
# pm.execute_notebook(
#     input_path=input_nb,
#     output_path=output_nb,
#     kernel_name="python3",
# )

import sys
print(sys.executable)

import sagemaker
print(sagemaker.__file__)

import sys
!{sys.executable} -m pip install --upgrade "sagemaker<3"

import sagemaker
print(sagemaker.__version__)

from sagemaker.pytorch import PyTorch

print("PyTorch Estimator import OK")

import sagemaker
from sagemaker.pytorch import PyTorch

role = sagemaker.get_execution_role()

estimator = PyTorch(
    entry_point="run_notebook.py",
    source_dir="monai-3d-job",
    role=role,
    framework_version="2.1",
    py_version="py310",
    instance_type="ml.g5.2xlarge",
    instance_count=1,
    volume_size=100,
    max_run=24 * 60 * 60,
)

#estimator.fit()
estimator.fit(wait=False, logs=False)

